### ISSUE TITLE
Transition docs to Documenter.jl and improve API docs

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/ValidatedNumerics.jl#105]
http://michaelhatherly.github.io/Documenter.jl/latest

**Comment by lbenet** [comment]
I've been playing using Documenter.jl and I like it a lot, though for a user guide I think it follows a bit short. I fully support this idea.

**Comment by dpsanders** [comment]
All sub-packages now have basic docs using Documenter.jl.
