### ISSUE TITLE
Test FastRounding to see if it is faster than changing the rounding mode

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/ValidatedNumerics.jl#150]
https://github.com/JeffreySarnoff/FastRounding.jl

**Comment by lbenet** [comment]
I think it is worth testing this, though I'm not in favor of eliminating `BigFloat` intervals.

**Comment by dpsanders** [comment]
This is not about replacing `BigFloat`, but about removing the need to change the rounding mode all the time for `Float64`. We certainly will not be replacing `BigFloat`! On the other hand, it will certainly be useful to have larger, fixed precision, like `DoubleDouble`, `ArbFloat`s, etc.

**Comment by dpsanders** [comment]
Ready in the `fast_rounding` branch.

**Comment by dpsanders** [comment]
https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/25
