### ISSUE TITLE
Add inf and sup functions

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/ValidatedNumerics.jl#252]
Compare pg. 64 of the IEEE 1788 standard.

`inf(a::Number)` should give the nearest float below `a`.

`inf(a::Interval)` should give the lower bound of `a`. We should use this consistently instead of `a.lo` throughout the code.

**Comment by lbenet** [comment]
I agree, though instead of `inf` and `sup` we should rather use `infimum` and `supremum`. Each time I see `inf` I think of `Inf` for `BigFloat`s: `typemax(BigFloat) --> inf`

**Comment by dpsanders** [comment]
This output should have changed in Julia v0.6 to no longer output inf.

**Comment by lbenet** [comment]
You are right; I didn't know that this was already corrected. Then I am in favor of `inf `and `sup`

**Comment by dpsanders** [comment]
Actually, I fixed it in https://github.com/JuliaLang/julia/pull/19939 ;)

**Comment by dpsanders** [comment]
For the record:
```
julia> big(Inf)
BigFloat(Inf, 256)
```

**Comment by dpsanders** [comment]
I don't think we should use `inf(a)` instead of `a.lo` throughout, in the end.

**Comment by dpsanders** [comment]
https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/48
