### ISSUE TITLE
Move to JuliaIntervals organisation?

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/ValidatedNumerics.jl#273]
Maybe it's time to create a JuliaIntervals organisation for interval-related pacakges.
What do you think, @lbenet ?

**Comment by lbenet** [comment]
Good idea! Aside from ValidatedNumerics, and IntervalConstraintProgramming, do you have another packages in mind?

**Comment by dpsanders** [comment]
I have an AffineArithmetic package in preparation; @jeffreysarnoff and/or I
will register FastRounding.jl, which gives almost a 10x (!) speed-up for
interval arithmetic operations (+, -, *, /).

Also, at some point I feel like the RootFinding submodule should be split
put into a separate package, as should interval contractors.

Later on we can anticipate TaylorModels etc.

Is JuliaIntervals a good name? Or Julia validated. Or maybe
JuliaValidatedNumerics and finally the current ValidatedNumerics.jl should
be renamed to IntervalArithmetic.jl.

Then ValidatedNumerics.jl can be a meta-package that automatically loads
some or all of the above packages. With the rewrite on progress of Pkg,
this kind of thing should be simplified.

**Comment by lbenet** [comment]
I like the idea of having ValidatedNumerics.jl as a meta-package. I think I prefer the name JuliaIntervals. I'm looking very much to play with `FastRounding.jl`!

**Comment by JeffreySarnoff** [comment]
I will register FastRounding.

**Comment by dpsanders** [comment]
Done: Now located at https://github.com/JuliaIntervals/ValidatedNumerics.jl.
