### ISSUE TITLE
I just took another look at the rounding mechanism here

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaIntervals/ValidatedNumerics.jl#277]
What are the strong advantanges, are there any drawbacks to this approach?

**Comment by dpsanders** [comment]
The advantage is that the user can change which rounding type is used by intervals (on Julia 0.6).

As far as I can tell, there is no performance penalty. Currently the only disadvantage is the annoying string of warnings when changing rounding type due to redefining many functions.

**Comment by JeffreySarnoff** [comment]
@dpsanders I am getting ready to register FastRounding later today.  If you have the time to see that it still does perform for you, let me know.  If there are pressing comments, also email me so any accommodation occur. Thank you.

**Comment by dpsanders** [comment]
I am currently travelling with no computer and bad Internet. But from what I can see, it looks good!

**Comment by dpsanders** [comment]
P

**Comment by JeffreySarnoff** [comment]
FastRounding has been merged.

**Comment by dpsanders** [comment]
Great, thanks! :+1:

**Comment by JeffreySarnoff** [comment]
FastRounding has been fixed
