### ISSUE TITLE
Where do we put the documentation

### ISSUE THREAD

**Issue by lbenet** [JuliaIntervals/ValidatedNumerics.jl#278]
I've done some work for the documentation to use Documenter.jl (which was proposed in #105), which is in the branch `documenter`. Among other things, it allows to test that the generated code is correct (doctests), which is always nice and useful. There is still a lot to be done, and I haven't touched much of the actual text, but that is not the point of this issue.

The question I would like to pose here is if `ValidatedNumerics.jl`, as the metapackage, should contain the documentation of all the packages, or if we should separate it for each package. I am in favor of the first option, but I think it is worth agreeing how to proceed. If we opt for the first option, I will begin updating (and probably reorganizing) the docs.

**Comment by dpsanders** [comment]
That's a good question.
It does seem reasonable to keep it in `ValidatedNumerics`, and then the docs for each separate package just end up being a link to the relevant section of the docs in VN, which should be separate pages I guess.

It's probably worth looking at how it's organised for example in DifferentialEquations.jl, where there is a similar structure. I think there may even be a separate docs package there, which could be a possibility too.

**Comment by lbenet** [comment]
In DifferentialEquations.jl they have two separated packages for the stable and the latest version, though maybe the same is doable with one package (I should check this). While their approach is quite clean, I think I'm not in favor of making independent PRs in different packages to keep everything properly updated.

I think I like better what is done in JuliaImages: they have docs for (some) different components, which are somehow centralized in a single doccumentation. I'll check how it works because I think that it is more self contained.

**Comment by dpsanders** [comment]
OK yes, that sounds good.

**Comment by lbenet** [comment]
I was wrong regarding JuliaImages: they do have juliaimages.github.io package for the documentation...

**Comment by dpsanders** [comment]
I don't see that there are different packages for the two sets of docs for DifferentialEquations.jl.
I think this should somehow be related to different branches ?

**Comment by dpsanders** [comment]
@ararslan suggested (offline) documenting each package separately, since otherwise it could be argued that there is too much modularity. I think this is a reasonable solution.

Then the global VN.jl docs can be examples that unify several of the sub-packages, for example, and link out to those subdocuments.

**Comment by lbenet** [comment]
In JuliaDiffEq they have DiffEqDocs.jl and DiffEqDevDocs.jl, but these refer to the usual docs and the developer-docs. Sorry for the confusion.

Regarding your last comment and the suggestion of @ararslan, in JuliaDocs they have (the package) juliadocs.github.io which somehow centralizes the docs of all packages, for both the stable and the latest versions. I think we should follow the model.

**Comment by dpsanders** [comment]
OK, let's try it like that for the moment then.
We can just keep the docs in the same `ValidatedNumerics.jl` repo, though.

**Comment by lbenet** [comment]
I've been working on the docs, mainly of IntervalArithmetics.jl simply to upgrade it to use Documenter.jl with html format. Since VN is a meta-package, I think it should have no specific documentation, but include in the README.md the corresponding badges pointing to the docs of the specific packages. @dpsanders Any opinion about this?

**Comment by lbenet** [comment]
Maybe even without the specific badges but only with a corrected README.md would be enough...

**Comment by dpsanders** [comment]
You had convinced me that all the docs for all the packages should be in one place... ;) But we can certainly try doing it like that and change later if necessary.

**Comment by lbenet** [comment]
Sorry for changing my mind. 😄 

I actually like that idea, but I dislike to commit in one package and the related docs in a different one. That's the reason I currently think it is better to have the docs in the same package, and cross-link them. That's the reason I was moving around the docs to `IntervalArithmetics.jl` mainly, and `IntervalRootFinding.jl`, aside from adapting things to use `Documenter.jl` with html format.

**Comment by dpsanders** [comment]
OK, fine with me. Feel free to open a pr even if you think it still needs some work.

**Comment by lbenet** [comment]
See https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/31 for work in progress.

**Comment by dpsanders** [comment]
I suggest just removing the stuff about `@intervalbox` from the docs.

**Comment by dpsanders** [comment]
Each package now has its own documentation using `Documenter.jl`.
