### ISSUE TITLE
Register with Zenodo to have a DOI

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/ValidatedNumerics.jl#279]
https://zenodo.org/

**Comment by lbenet** [comment]
I fully agree, though I think we should bring everything to a stable form before.

**Comment by dpsanders** [comment]
This came up [here](https://discourse.julialang.org/t/are-rationals-that-expensive/1374/26?u=dpsanders), so I guess it's reasonably urgent. In any case, I understand that Zenodo automatically gives a new DOI for each new release.

**Comment by dpsanders** [comment]
The package has already been registered with Zenodo.

**Comment by lbenet** [comment]
Fine with closing this issue. One single comment: It is probably a good idea to include a DOI badge in the README.md page, probably with indications how to cite the package.
