### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaIntervals/ValidatedNumerics.jl#282]
http://dpsanders.github.io/ValidatedNumerics.jl

Notice it points to the old location.

**Comment by ChrisRackauckas** [comment]
This is the link at the top of the repo, so I can't PR for it. It should be

http://juliaintervals.github.io/ValidatedNumerics.jl/

**Comment by dpsanders** [comment]
Fixed, thanks.

Note that the docs are due for a pretty major overhaul, since we have now (on master) split VN into various repos. If you checkout master of VN, it will automatically pull in all the pieces. We followed the DiffEq example ;)
